services:
  webui:
    build: .
    volumes:
      - type: bind
        source: ./models
        target: /webui/models
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]